config/routes.rb
Rails.application.routes.draw do
    resources :tourists
    root 'top#main'
    post 'top/login'
    get 'top/login'
    get 'top/logout'
    get 'top/main'
    get 'get_tourist/:name', to: 'tourist#get_tourist'
    resources :hotels
    get 'get_image/:id', to: 'hotels#get_image'
    get 'search' => 'hotels#search'
    resources :reviews
    
    post 'hotels/create'
    root 'hotelsx#index'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/hotel.rb
class Hotel < ApplicationRecord
    has_many :reviews
    
    def self.search(keyword)
        where(["hname like? OR comment like? OR sptype like?","%#{keyword}%","%#{keyword}%","%#{keyword}%"])
    end
end

app/models/review.rb
class Review < ApplicationRecord
    belongs_to :hotel
    belongs_to :tourist
end

app/models/tourist.rb
class Tourist < ApplicationRecord
has_many :reviews
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
private
    def current_tourist
        if session[:login_name]
            tourist = Tourist.find_by(name: session[:login_name])
        else
            tourist = Tourist.create
            session[:lonin_name] = tourist.name
        end
        tourist
    end
    helper_method :current_tourist
end

app/controllers/hotels_controller.rb
class HotelsController < ApplicationController
    def index
        @hotels = Hotel.all
    end
    
    def new
        @hotel = Hotel.new
    end
    
    def create
        place = params[:hotel][:place]
        hname = params[:hotel][:hname]
        comment = params[:hotel][:comment]
        price = params[:hotel][:price]
        
        sptype = params[:hotel][:sptype]
        
        img = params[:hotel][:img].read
        hotel = Hotel.new(place: place, hname: hname, comment: comment, price: price, sptype: sptype, img: img)
        if hotel.save
            redirect_to hotels_path
        else
            render'new'
        end
    end
    
    
    def destroy
        hotel = Hotel.find(params[:id])
        hotel.destroy
        redirect_to hotels_path
    end
    
    def get_image
        hotel = Hotel.find(params[:id])
        send_data hotel.img, disposition: :inline, type: 'image/png'
    end
    
    def show
       @hotel = Hotel.find(params[:id]) 
    end
    
    def search
        @hotels = Hotel.search(params[:keyword])
        @keyword = params[:keyword]
        render "index"
    end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
    def index
        @reviews = Review.new(hotel_id: params[:hotel_id])
    end
    
    def new
        @review = Review.new(hotel_id: params[:hotel_id])
    end
    
    def create
       @review = Review.new(
       hotel_id: params[:review][:hotel_id],star: params[:review][:star],
       rcomment: params[:review][:rcomment],tourist_id: current_tourist.id)
        if @review.save
           redirect_to controller: :hotels, action: :show, id: params[:review][:hotel_id]
        else
            render 'new'
        end
       
    end
    
    def destroy
        review = Review.find(params[:id])
        hotel_id =review.hotel_id
        review.destroy
        redirect_to controller: :hotels, action: :show, id: hotel_id
    end
    
end

app/controllers/top_controller.rb
class TopController < ApplicationController
  def main
    render 'login'
  end

  def login
    tourist = Tourist.find_by(name: params[:name])
    if tourist and BCrypt::Password.new(tourist.pass) == params[:pass]
      session[:login_name] = tourist.name
      redirect_to controller: :hotels , action: :index
    else
      render 'login'
    end
  end

  def logout
    session.delete(:login_name)
    redirect_to root_path
  end
end

app/controllers/tourists_controller.rb
class TouristsController < ApplicationController
    def index
    @tourists = Tourist.all
    end

    def new
    @tourist = Tourist.new
    end

    def create 
      @tourist = Tourist.new(
      name: params[:tourist][:name],
      pass: params[:tourist][:pass])
      if @tourist.valid?
        flash[:notice] = '追加しました'
        @tourist.pass = BCrypt::Password.create(params[:tourist][:pass])
        @tourist.save
        redirect_to tourists_path
      else
        render 'new'
      end
    end

    def destroy
      tourist = Tourist.find(params[:id])
      tourist.destroy
      redirect_to tourists_path
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hotels_helper.rb
module HotelsHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/helpers/top_helper.rb
module TopHelper
end

app/helpers/tourists_helper.rb
module TouristsHelper
end

app/views/hotels/index.html.erb
<%= image_tag "yado.jpeg", class: 'img' %>
<h2>九州のおすすめ温泉宿を検索できます</h2>
<%= link_to 'ログアウト', top_logout_path %>　
<%= link_to'宿を登録', new_hotel_path %>

<div href="#"class="search-form">
    <%= form_with url: search_path ,method: :get, local: true do |f| %>
        <%= f.text_field :keyword, value: @keyword, placeholder: "温泉の特徴を検索できます" %>
        <%= f.submit "検索" %>　▶
        <%= link_to '検索リセット', :action => 'index' %>
        
    <% end %>
</div>
<div class ="hotel-list">
<% @hotels.each do |hotel| %>
<p>
    <hr>
    <%= image_tag "/get_image/#{hotel.id}" , class: 'image' %>
    <br>
    
    <div class = "flex">
    温泉旅館:<%= link_to hotel.hname , "/hotels/#{hotel.id}" %>
    <br>
    所在地:<%= hotel.place %><br>

    1泊/<%= hotel.price %>円
    <br>
    コメント：<%= hotel.comment %><br>
    </div>
    温泉の特徴:   <%= hotel.sptype %>
    <br>
    <%= link_to'削除',"/hotels/#{hotel.id}", method: :delete %>
    <% end %>
</p>
</div>

app/views/hotels/new.html.erb
<%= image_tag "yado.jpeg", class: 'img' %>
<h2>九州のおすすめ温泉宿を登録できます</h2>

<%= form_for @hotel, url: {action: :create} do |f| %>
    <%= f.label :hname,'ホテル名　'%>
    <%= f.text_field :hname %><br>
    <%= f.label :place,'県　　　　'%>
    <%= f.select :place,['福岡','佐賀','長崎','大分','熊本','宮崎','鹿児島'] %><br>
    <%= f.label :price,'価格　　　'%>
    <%= f.text_field :price %><br>
 
    <%= f.label :sptype,'温泉の特徴'%>
    <%= f.text_field :sptype %><br>
    
    <%= f.label :comment,'紹介文　　'%>
    <%= f.text_field :comment %><br>
    <%= f.label :img, 'イメージ　'%>
    <%= f.file_field :img %><br>
    <%= link_to '戻る', :action => 'index' %>
    <%= f.submit"登録" %>
    
<% end %>

app/views/hotels/show.html.erb
<p>
<%= image_tag "yado.jpeg", class: 'img' %>
<h2>九州のおすすめ温泉宿を検索できます</h2>
<%= link_to 'ログアウト', top_logout_path %><br><hr>

   <br>
</p>
    <%= image_tag "/get_image/#{@hotel.id}" , class: 'image' %><br>

<p>
   温泉宿:<%= @hotel.hname %><br>
    <strong>所在地</strong>
    <%= @hotel.place %>県
    <br>
    <strong>値段</strong>
    1泊 / <%= @hotel.price %>円<br>
    <strong>旅館からのコメント</strong>
    <br>
    <%= @hotel.comment %>
    <br>
    </p>
    
    <p>
    <strong>お客様の声</strong>
    <br>
    <% @hotel.reviews.each do |e| %>
        <p>
            コメント: <%= e.rcomment %>, 
            評価: <%= e.star %>, 
            投稿者: <%= Tourist.find(e.tourist_id).name %>
            <% if e.tourist_id == current_tourist.id %>
                <%= link_to '削除' , review_path(e), method: :delete %>
            <% end %>
        </p>
    <% end %>
</p>
<hr>
<p>
    <%= link_to 'レビューを投稿する', new_review_path(hotel_id: @hotel.id) %>
</p>
    <%= link_to 'TOPに戻る', :action => 'index' %>
</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Yado2</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/reviews/new.html.erb
<% 
    if @review.errors.present?
        @review.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
        <% end %>
<% end %>


<%= form_for @review, url: {action: :create} do |f| %>
    <p>'ホテル名： <%= Hotel.find(@review.hotel_id).hname %></p>
    <%= f.hidden_field :hotel_id %>
    <p>投稿者： <%= Tourist.find(current_tourist.id).name %></p>
    <%= f.hidden_field :tourist_id %>
    <p><%= f.label :rcomment, 'コメント' %>
    <%= f.text_field :rcomment %></p>
    <%= f.label :star, '1', value: 1 %>
    <%= f.radio_button :star, '1' %>
    <%= f.label :star, '2', value: 2 %>
    <%= f.radio_button :star, '2' %>
    <%= f.label :star, '3', value: 3 %>
    <%= f.radio_button :star, '3' %>
    <%= f.label :star, '4', value: 4 %>
    <%= f.radio_button :star, '4' %>
    <%= f.label :star, '5', value: 5 %>
    <%= f.radio_button :star, '5' %>
    </p>
    <p><%= f.submit 'コメントを登録する' %></p>
    
    <%= %>
<% end %>

app/views/top/login.html.erb
<br>
<%= image_tag "yado.jpeg", class: 'img' %>
<h2>九州のおすすめ温泉宿を検索できます</h2>

<session class = "main">
  <div class = "lin1">
    <%= form_tag top_login_path, method: :post do %>
    <div class = "lin1_1">
      <h3>宿ログに登録済みの方</h3>
    </div>
    <div class = "lin1_2">
      <%= label_tag :name, 'ユーザ名　' %>
      <%= text_field_tag :name %> <br>
      <%= label_tag :pass, 'パスワード' %> 
      <%= password_field_tag :pass %>　
      <%= submit_tag 'ログイン' %>
    </div>
  <% end %>
  <pre><br>
  </div>
</session>

<session class = "side">
  <div class = "lin2">
    <div class = lin2_1>
      <h3>初めて利用される方</h3>
    </div>
    <div class = lin2_2>
      <%= link_to 'ユーザー登録', "/tourists/new" %>
    </div>
  </div>
</session>

app/views/tourists/index.html.erb
<% if flash[:notice] %>
  <%= flash[:notice] %>
<% end %>
<% @tourists.each do |e| %>
  <p>
    <% e.name %>
    <% e.pass %>
    <% link_to '削除', tourist_path(e), method: :delete %>
  </p>
<% end %>
<p>
<cener>ユーザ登録が完了しました<br>
<%= link_to 'ログイン画面', top_login_path %>
</center>
</p>

app/views/tourists/new.html.erb
<%= image_tag "yado.jpeg", class: 'img' %>
<h2>九州のおすすめ温泉宿を検索できます</h2>

<div class = "lin">
<%= form_for @tourist, url: {action: :create} do |f| %>
<center>
  <h3>新規ユーザー登録</h3>
  <%= f.label :name, 'ユーザ名　' %> 
  <%= f.text_field :name %> <br>
  <%= f.label :pass, 'パスワード' %> 
  <%= f.password_field :pass %><br>
　<%= link_to '戻る', '/' %>　　
  <%= f.submit '登録' %>
</center>
<% end %>
</div>